# Jupyter notebooks
- id: ipynb-output-strip-check
  name: ipynb-output-strip-check
  description: check if notebook outputs and metadata are empty
  files: \.ipynb$
  stages: [commit]
  language: python
  entry: ipynb-output-strip-check
- id: ipynb-output-strip
  name: ipynb-output-strip
  description: strip all outputs and metadata from notebooks. This also removes the output of the notebook in the workingdir
  files: \.ipynb$
  stages: [commit]
  language: system
  entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --ClearMetadataPreprocessor.enabled=True --inplace
