# Jupyter notebooks
- id: check-ipynb-output-strip
  name: check-ipynb-output-strip
  description: check if notebook outputs and metadata in staging area are empty
  files: \.ipynb$
  stages: [commit]
  language: python
  entry: check-ipynb-output-strip
- id: ipynb-output-strip
  name: ipynb-output-strip
  description: strip all outputs and metadata from notebooks. This also removes the output of the notebook in the workingdir
  files: \.ipynb$
  stages: [commit]
  language: system
  entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --ClearMetadataPreprocessor.enabled=True --inplace
